name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: my-portfolio-app  

    - name: Build the app
      run: npm run build
      working-directory: my-portfolio-app  

    - name: Configure Git user
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
      working-directory: my-portfolio-app 

    - name: Deploy to GitHub Pages
      run: npm run deploy
      working-directory: my-portfolio-app  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
